### ISSUE TITLE
sono spasciato, ma da qualche parte devo iniziare

### ISSUE THREAD

**Issue by cirospat** [SiciliaHub/accussi#1]
accussi:
http://accussi.opendatasicilia.it/

ora devo far spuntare nella prima colonna il titolo del tutorial scritto nella prima colonna del database: https://docs.google.com/spreadsheets/d/1f1XJw37V6W8wzV9tupzC0XaK7xAWakRGxU7e3dQlgVQ

poi ci sono tante cose da limare ad esempio icona (mnkia valla a trovare un icona per "Accussì")
cmq andiamo per step , asinnò (altrimenti), mi confondo

**Comment by giuragu** [comment]
@cirospat se vuoi faccio io il puntamento al titolo...

**Comment by aborruso** [comment]
@giuragu c'è bisogno di te (io ci sono comunque).

@cirospat apro una nuova issue per le icone

**Comment by cirospat** [comment]
@giuragu 
grazie, fatto

c'è smurritiari (ci devo smanettare) 
this is the girlfriend

**Comment by cirospat** [comment]
il lavoro sembra quasi terminato,
è stata una bella avventura di 24 ore per me,
perchè è stata l'occasione per familiarizzare con il codice html per la costruzione di una pagina web e della sua architettura. E di strummintiare (sperimentare) con le potenzialità di Github.
@aborruso e @giuragu  sono stati i miei tutor che mi hanno guidato nella costruzione di <code>Accussì</code>. grazie

Insomma sono meno spasciato ora

**Comment by cirospat** [comment]
sono spasciato ma Accussì è nato
ci ho sbattuto la faccia con il codice html ed è andata
grazie ragazzi
