### ISSUE TITLE
scegliere icona

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/accussi#2]
Io @cirospat inizierei da qui https://thenounproject.com/search/?q=study

Occhio alle licenze

**Comment by cirospat** [comment]
https://thenounproject.com/search/?q=study&i=975009

come vi pare questa?
colore arancione
![image](https://cloud.githubusercontent.com/assets/3757525/26308840/2450c91c-3efb-11e7-969d-756898a347e7.png)

**Comment by giuragu** [comment]
@cirospat un'immagine da "formazione" ma non dia il messaggio solo della lezione ma anche della condivisione. Provo a cercare qualcosa anch'io

**Comment by cirospat** [comment]
@giuragu si cerca una cosa anche tu
considera che è la mia prima esperienza di petrusinizzazione di un database
quindi la richiesta di help nel fare questa cosetta per me è di default ;-) 
grazie

**Comment by giuragu** [comment]
@cirospat è sempre un piacere. allo stesso tempo però la mia velocità nell'intervenire non è la stessa della vostra. Vi prego di scusarmi per questo :)

**Comment by cirospat** [comment]
@giuragu sono io che mi devo scusare per il mio rompere le scatole con queste cose (petrusinizzazione di database)

**Comment by cirospat** [comment]
@giuragu @aborruso 
https://thenounproject.com/term/study/38932/
questa vi piace?
![image](https://cloud.githubusercontent.com/assets/3757525/26308818/fd52ebf6-3efa-11e7-95d4-68e333266e28.png)

**Comment by giuragu** [comment]
@cirospat questi due danno quel senso che immaginavo di "tutoring": https://thenounproject.com/search/?q=tutoring&i=510086 o https://thenounproject.com/search/?q=tutoring&i=66723

**Comment by cirospat** [comment]
@giuragu  questo mi piace, da calore
https://thenounproject.com/search/?q=tutoring&i=510086
![image](https://cloud.githubusercontent.com/assets/3757525/26310062/ba490476-3eff-11e7-9b82-b6924f10d793.png)

**Comment by cirospat** [comment]
ma anche questo mi piace
https://thenounproject.com/search/?q=tutoring&i=66723
![image](https://cloud.githubusercontent.com/assets/3757525/26310130/ffb1dc04-3eff-11e7-94a6-437f9e64a60a.png)

**Comment by cirospat** [comment]
@giuragu 
scegli tu
mi fido :-)

**Comment by giuragu** [comment]
@cirospat Il primo mi piace molto solo che gli taglierei il dito al tutor. Mi da una sensazione di comando che mi da fastidio

**Comment by cirospat** [comment]
Sono fuori, senza PC
Più tardi provo a tagliare il dito con un photo editor.
Debbo salvare in .PNG  vero?

**Comment by cirospat** [comment]
O va bene anche in JPEG?

**Comment by cirospat** [comment]
![image](https://cloud.githubusercontent.com/assets/3757525/26318475/7db1acb8-3f1b-11e7-81b8-14f325f8c6f5.png)

ho cancellato il dito
come vi pare?
Ma si è cancellato un po di sottofondo (i quadratini grigio chiari), è un problema?

**Comment by giuragu** [comment]
@cirospat molto molto meglio

**Comment by aborruso** [comment]
Per fare la scelta, guardatela anche in piccolo, riducetela a 32 x 32

![image](https://cloud.githubusercontent.com/assets/30607/26318580/e464e8bc-3f1b-11e7-8ac2-7d96de98c6a5.png)

A me sembra troppo ricca. Io però mi ritiro da questa scelta, fate vobis :)

**Comment by cirospat** [comment]
allora ci mettiamo questa (che è anche bella)?
![image](https://cloud.githubusercontent.com/assets/3757525/26318695/4903a92a-3f1c-11e7-81cf-00079dc4f548.png)

guidatemi per il prossimo step.
Immagino si deve caricare il file in formato .PNG in dimensioni 32x32 dentro la directory  accussi/img/
Giusto?

**Comment by cirospat** [comment]
![image](https://cloud.githubusercontent.com/assets/3757525/26318815/b6fe004c-3f1c-11e7-943c-c7f0d9a9558b.png)

come vi pare 32x32 questa?

**Comment by cirospat** [comment]
ho fatto una prova
ho caricato il file accussi_favicon.png (32x32)
l'ho applicato al favicon e al logo dell'index page

che ve ne pare?

**Comment by aborruso** [comment]
@cirospat non è trasparente ed è deformato.

Faccio una modifica io

**Comment by aborruso** [comment]
Per me ora si può chiudere

**Comment by cirospat** [comment]
prima di chiudere, in maniera zen, come si fa a farlo venire trasparente?
Si agisce nel codice html della pagina? 
Oppure?

**Comment by aborruso** [comment]
@cirospat se apri una PNG trasparente, la ridimensioni e la salvi, la PNG sempre trasparente sarà.

Salvo che tu non stia usando un programma "brutto" o abbia volutamente rimosso la trasparenza.

Su win usando [paint.net](https://www.getpaint.net/) o gimp non avresti avuto problemi. Tu cosa hai usato?

**Comment by cirospat** [comment]
credo che ho usato un programma brutto, 
paint, 
per fare cose a volo

**Comment by giuragu** [comment]
@aborruso Ok buono così :)

**Comment by cirospat** [comment]
thanks
