### ISSUE TITLE
scegliere un colore di base

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/accussi#3]
Per petrusino è un verde.

**Comment by cirospat** [comment]
andiamo di arancione ?

**Comment by aborruso** [comment]
@cirospat "Fare o non fare Non c'è provare"

Basta che modifichi il [CSS](https://github.com/SiciliaHub/accussi/blob/gh-pages/css/style.css#L48).

E modificare tutte le volte che trovi il verde `#47A447` di petrusino.

Dopo che lo modifichi, tocca fare qualche refresh

**Comment by cirospat** [comment]
cambiato in #F38F19 
su accussi/css/style.css

vi piace l'arancione?

**Comment by giuragu** [comment]
@cirospat farei più scuretto forse

**Comment by cirospat** [comment]
@giuragu 
allora ho cambiato in #DE6A0F

**Comment by cirospat** [comment]
se piace il colore chiudo l'issue

**Comment by aborruso** [comment]
@cirospat finché c'è quella [linea verdina](https://github.com/SiciliaHub/accussi/blob/gh-pages/css/style.css#L18) prima del footer, non lo puoi chiudere :)

**Comment by cirospat** [comment]
ok ho cambiato il parametro numerico per il colore prima del footer
thanks for training me
