### ISSUE TITLE
sezione "Proponi" - problems

### ISSUE THREAD

**Issue by cirospat** [SiciliaHub/accussi#4]
nella pagina html di Proponi
ho cambiato tutto ciò che era Petrusino in Accussì
ma succede questo
http://accussi.opendatasicilia.it/proponi.html

sono appagnato (confuso e senza un barlume di direzione da seguire per rimediare)

**Comment by aborruso** [comment]
Me la sono assegnata

**Comment by aborruso** [comment]
@cirospat fatti un account su [disqus](disqus.com) con la tua email gmail

**Comment by cirospat** [comment]
già ce l'ho
https://disqus.com/by/cirospat/

**Comment by aborruso** [comment]
#closed http://accussi.opendatasicilia.it/proponi.html
