### ISSUE TITLE
preparare metainfo per la condivisione sui social

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/accussi#7]
- [ ] facebook opengraph
- [ ] twitter card

**Comment by cirospat** [comment]
e
- [ ] google+ card

**Comment by aborruso** [comment]
@cirospat bastano le prime due, quella di google diciamo che si adatta su quella di fb

**Comment by cirospat** [comment]
la condivisione su Google+ mi fa aprire la pagina con il nuovo screeenshot dell'index di Accussì (già caricata su IMG), mentre quella di FB mi da la vecchia pagina di Petrusino
Strano

**Comment by aborruso** [comment]
@cirospat io ancora non ho fatto nulla.

E in ogni caso non è ancora il momento per condividere IMHO

**Comment by cirospat** [comment]
no, non è per condividere ora, certo fino a quando non è tutto ok in tutte le pagine non c'è da condividere nulla,
volevo solo inserire i giusti contenuti nel codice delle condivisioni sui social.

**Comment by aborruso** [comment]
On 22 May 2017 at 22:31, ciro <notifications@github.com> wrote:

> volevo solo inserire i giusti contenuti nel codice delle condivisioni sui
> social.
>

Dammi il tempo di farlo per la home, e poi vai di copia e incolla.

Grazie

___________________

Andrea Borruso
website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E, EPSG:4326
___________________

"cercare e saper riconoscere chi e cosa,
 in mezzo all’inferno, non è inferno,
e farlo durare, e dargli spazio"

Italo Calvino

**Comment by cirospat** [comment]
Grazie a te,
domani praticamente abbiamo finito, ultimi ritocchini....
