### ISSUE TITLE
adattare la pagina Open

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/accussi#8]
Modificare il testo in modo da renderlo relativo a `accussì`

**Comment by cirospat** [comment]
fatto per `HTML` e `CSV`  :-)
ancora da fare per `datapackage` in JSON

**Comment by aborruso** [comment]
C'è anche da modificare 

![image](https://cloud.githubusercontent.com/assets/30607/26320442/33683b7e-3f23-11e7-93a8-c5b74041850e.png)

**Comment by cirospat** [comment]
modificato lo schema dati
e 
modificato il `datapackage` in JSON
