### ISSUE TITLE
cambiare favico e logo in tutte le pagine

### ISSUE THREAD

**Issue by aborruso** [SiciliaHub/accussi#9]
In cosa è, proponi, c'è ancora il prezzemolo

**Comment by cirospat** [comment]
lo so 
sto studiando ancora da dove prendi limmagine per favicon e logo su index che hai aggiustato.
E' sempre il file accussi_favicon.png ?
Perchè vedo anche un altro accussi_full.png, ma non lo trovo sul codice della pagina index
![image](https://cloud.githubusercontent.com/assets/3757525/26320720/3394047e-3f24-11e7-8cf4-3296c4e1214c.png)

**Comment by aborruso** [comment]
@cirospat devi cercare i riferimenti nelle pagine e cambiare il nome del file:

- [qui](https://elezioni.comune.palermo.it/elezioni-amministrative-2017.php?fc=14&tp=47) ad esempio;
- [qui](https://github.com/SiciliaHub/accussi/blob/gh-pages/cosa.html#L53)

**Comment by cirospat** [comment]
cambiati favicon e logo in tutte le pagine
